### ISSUE TITLE
Updating links

### ISSUE THREAD

**Issue by nyarly** [XingFramework/Relayer#16]
Use case discovered with @TablesawTablesawsen today:

We have a resource that hasOne another - specifically userState.hasOne('currentProject', Project);

The trick is, we want to be able to update the current project by updating the link. hasOne doesn't create the equivalent getters and setters, so that's tricky.

Current solution is to create a separate `.property('currentProjectLink', '$.links.current_project');`

The question that merits discussion: is the solution to this merely to accept and document that as best practice? Safely create the property automatically? Or something more exotic like akin to AR's associations: `userState.currentProject = otherProject`, which updates the link from the `self` of otherProject?

**Comment by hannahhoward** [comment]
assuming 'userState' is your user state instance, and 'project' is the project you want to assign.
userState.currentProject().set(project.templatedUrl)
