### ISSUE TITLE
Subclassing Resource

### ISSUE THREAD

**Issue by nyarly** [XingFramework/Relayer#5]
_From @nyarly on August 29, 2015 0:53_

MSW team discovered an issue with _old_ resources where

Resource
  ApplicationThing
    SpecializedAppThing

Doesn't work because the errorResource of SpecializedAppThing doesn't have defineJsonProperty. Not positive that Relayer has this issue, but there should be a test for same.

_Copied from original issue: LRDesign/relayer#9_

**Comment by hannahhoward** [comment]
Relayer does in fact setup errors as a subclass and define the specific properties on that class. Closing... unless you want specific code examples or further testing.
