### ISSUE TITLE
Consuming old APIs

### ISSUE THREAD

**Issue by nyarly** [XingFramework/Relayer#6]
_From @nyarly on August 18, 2015 18:16_

This is more of a general question: how do we handle responses from older API servers? At present, a missing link will raise an error on load(), which e.g. crashes a ui-router resolve.

One idea: general error handling, so that we could plug e.g. lrdToast into a relayer resource and have load errors handled there.

Another idea: something like 

```
resources.bigThing().optionally.littleThing().orElse(() =>  buildDummyLittleThing());
```

If we know that we're moving ahead of the backend.

Ultimately, the two are equivalent, just moving the responsibilities around. Arguably, the first is better because we could isolate the "future backend" expectations and start implementing them.

And the extreme end, this provides for a way to prototype in the browser and implement the server functionality required by the prototype, as well as providing detached FE testing.

_Copied from original issue: LRDesign/relayer#8_

**Comment by hannahhoward** [comment]
I don't understand the specific request here. As such I don't think this ticket is actionable.
